### ISSUE TITLE
Error luego de instalar

### ISSUE THREAD

**Issue by lupa18** [tryolabs/libreQDA#11]
El servidor corre sin problemas, pero al abrir el navegador, aparece:

Non-ASCII character '\xc3' in file /home/lupa/libreqda/libreQDA/libreqda/views.py on line 394, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details (views.py, line 394)

**Comment by maurodec** [comment]
Lupa, esto está pasando por un commit parcial que hice pra poder seguir trabajando desde casa. Apenas termine el feature va a quedar arreglado. Si querés probar la última version te recomiendo que uses una revisión anterior.

Saludos,
Mauro.
