### ISSUE TITLE
Internacionalización

### ISSUE THREAD

**Issue by ghost** [tryolabs/libreQDA#14]
Usar rosetta para traducir textos

**Comment by marcbria** [comment]
¿Estas indicaciones parecen adecuadas?
http://django.es/blog/traduce-tus-proyectos-django-con-rosetta/

**Comment by marcbria** [comment]
Sigo las indicaciones y para mi sorpresa, veo que la aplicación ya se ha instalado:
http://demo.libreqda.edu.uy/rosetta

Sugiero crear un nuevo grupo llamado "traductorxs" (en http://demo.libreqda.edu.uy/admin) y dotarles de los permisos necesarios para iniciar la traducción.

**Comment by marcbria** [comment]
De esta incidencia sale un nuevo caso para cada idioma para el que se requiera traducción.
Se acordó que la 1.0 saldría en Español (es_ES y es_UY) y portugués (pt_BR).
