### ISSUE TITLE
Subidas de documentos

### ISSUE THREAD

**Issue by paribanufreitas** [tryolabs/libreQDA#22]
Probé con un mismo documento en diferentes formatos obteniendo los siguientes resultados:

PDF. Sube pero el formato es malo, no se respetan los saltos de párrafos, haciendo la lectura insoportable.

RTF y DOC. Aparece mensaje "Oops, hubo un error en la carga".

ODT. No levanta

**Comment by marcbria** [comment]
Es un duplicado del #20. Revisen incidencias previas y comenten allí antes de publicar nuevas.
