### ISSUE TITLE
Problemas con punto y coma

### ISSUE THREAD

**Issue by paribanufreitas** [tryolabs/libreQDA#25]
Si se fijan en un proyecto que yo he creado con mi usuario hay dos versiones del mismo documento, una con puntos y comas y otro sin. 
Resulta que descubrí la presencia del punto y coma en el texto del documento imposibilita codificar texto a un lado y otro de su presencia.

Ejemplo, ante el siguiente texto:

11111 1111 1111111111111 1111 ; 22222 22222222 22222 22222222

Me deja cofificar o todo lo que quiera de 1's  o todas las variaciones de 2, pero no me deja codificar " 1111 ; 22222 22222222"

Probé subiendo un documento sin punto y coma y sustituyéndolo por un punto siempre y si puedo codificar   "1111 . 22222 22222222"

**Comment by amartinezuy** [comment]
Acabo de subir un cambio que creo arregla este problema. Si se confirma que los soluciona cerramos el issue.

**Comment by paribanufreitas** [comment]
Gracias Alejandro.
Me imagino que es una pavada sintáctica, y fue de cuete que lo ví! jajaj :)
Ahora mismo no puedo chequear, estoy preparando una clase para mañana.
Pero en cuanto pueda lo reviso.

Saludos.

PD. Vengo documentando bien o escribo una tesis por Issue? jajaj Es mi
primera experiencia! :)

## 

Asist. Lic. Paribanú Freitas
Instituto de Fundamentos y Métodos en Psicología
Facultad de Psicología
UDELAR
http://about.me/paribanufreitas

Tel. (598)2400 85 55/ int. 340
Tristán Narvaja 1674 CP 11200
Montevideo, Uruguay

2013/4/1 Alejandro Martínez notifications@github.com

**Comment by amartinezuy** [comment]
Creo que si !

Lo más importante es explicar claramente el problema y dar los pasos para poder reproducirlo. De esta forma quién vaya a arreglarlo puede reproducir el error, ver los motivos que lo provocan, y finalmente resolverlos.

Aprovecho para comentarte que arreglé un problema bastante molesto con las barras de citas en documentos largos (se veían más abajo de lo que deberían en algunos casos).

**Comment by marcbria** [comment]
Se resuelve el problema del ";" pero aparece uno nuevo con las barras de citas.
Reporto en XXX.

**Comment by marcbria** [comment]
El problema al que me refería (la altura de las barras no es correcta y se convierten en "pelotas") no aparece en los documentos nuevos, creados tras actualizar el fuente, por lo que no se abre un nuevo bug, ya que se llega a la conclusión de que era debido a un conflicto entre los datos de posicionamiento en la BD y la nueva versión del código.

**Comment by paribanufreitas** [comment]
Paribanu Freitas te envió una invitación

Twitter te ayuda a estar conectado con lo que está sucediendo en estos momentos y con las personas y organizaciones que te importan.

```
Aceptar invitación
```

https://twitter.com/i/14d6b0b7-9e15-4d0b-84eb-f94b0bb6e10f

## 

Este mensaje fue enviado por Twitter en nombre de los usuarios de Twitter que ingresaron tu dirección de correo electrónico para invitarte a Twitter.
Eliminar subscripción: https://twitter.com/i/o?t=1&iid=b8f371e4ce624049b3370beaeb361446&uid=0&c=IuVwbCB3dgGbzUKjOXhFXdLICBYKz5Ncu06qlkelzAd5pFtEk%2BIKC%2BCNIW2mTDpgOK66xpmSwBPeqLJZwbyRVo0V3qkTqpSzVhQcN4hAZEaGTGydddPyLg%3D%3D&nid=9+26

¿Necesitas ayuda?
https://support.twitter.com
