### ISSUE TITLE
Intersección en consultas avanzadas

### ISSUE THREAD

**Issue by jmunoz298** [tryolabs/libreQDA#38]
Si entiendo bien la idea de "intersección" (y yo diría que sí), no está funcionando correctamente:
Ejemplo: 
CodigoA: cita1, cita2, cita3, cita4, cita5
CodigoB: cita4, cita5, cita6, cita7
CodigoC: cita3, cita5, cita8

CodigoA y CodigoB = cita4, cita5 
CodigoA y CodigoC = cita3, cita5

La consulta avanzada de unión de las dos anteriores da como resultado (correcto): cita3, cita4, cita5

La consulta avanzada de intersección de las don anteriores da como resultado (incorrecto): "no hubo resultados", cuando lo correcto sería: cita5

¿o estoy interpretando mal la intersección?

**Comment by maurodec** [comment]
Juan, había un error al ejecutar las consultas. Ya está arreglado.

**Comment by jmunoz298** [comment]
Confirmado
