### ISSUE TITLE
Consultas semánticas: UP

### ISSUE THREAD

**Issue by jmunoz298** [tryolabs/libreQDA#39]
La opción "UP" da resultados incorrectos, puesto que sólo muestra las citas del nivel inmediatamente superior (mientras que DOWN muestra la de todos los niveles.

Es decir, si tenemos la siguiente estructura

Codigo1
--Codigo1.1
----Codigo1.1.1

La opción DOWN, aplicada al Codigo1 muestra las citas de Codigo1, Codigo1.1 y Codigo1.1.1
mientras que la opcion UP aplicada al Codigo1.1.1 muestra sólo las citas de Codigo1.1.1 y Codigo1.1 (pero no las de Codigo1)

**Comment by maurodec** [comment]
Juan, según el documento de consultas:

> Recupera las citas relacionadas con el código y sus superiores directos (sólo un nivel).

En caso de que se quiera se puede crear un nuevo issue para crear un nuevo tipo de consultas marcado como enhancement.

**Comment by jmunoz298** [comment]
Tienes razón. Lo dejaremos así por el momento
