### ISSUE TITLE
Menú

### ISSUE THREAD

**Issue by jmunoz298** [tryolabs/libreQDA#42]
Tras la última actualización "Branch coocurrencias" ha desparecido la barra de menú en la vista de documentos

**Comment by maurodec** [comment]
Juan,
Ese mensaje sólo se encuentra ahí para que sepan que se encuentran en la branch correcta. Ua vez que confirmen que el comportamiento de las coocurrencias es correcto, voy a eliminar ese mensaje y haré los cambios en master.
