### ISSUE TITLE
Error al subir un pdf

### ISSUE THREAD

**Issue by lupa18** [tryolabs/libreQDA#6]
Este es el PDF que se intentó subir: http://impropriedades.files.wordpress.com/2011/07/vieira_what_kind_of_a_commons_is_free_software.pdf

El error:

Warning at /project/2/document/add/
Incorrect string value: '\xEF\xAC\x82ypr...' for column 'text' at row 1

Ver captura:

![Captura de pantalla de 2013-02-22 17:16:43](https://f.cloud.github.com/assets/463429/186211/7891cc3a-7d24-11e2-811e-df005854d6f7.png)

**Comment by maurodec** [comment]
El error es producido por el encoding utilizado en la base de datos. He actualizado el README.

Ver commit bd92577a34299a274ab49f3c5b9bfc0325e6e6e4.
